package-lock.json, package.json, src/app/app.component.ts, src/app/app.module.ts, src/app/shared/UI/basic-uses-avatar/basic-uses-avatar-component.ts, src/app/shared/UI/basic-uses-avatar/basic-uses-avatar.module.ts, src/app/shared/shared.module.ts
=> alyle.ui init

src/app/user/components/user-modify.component.ts, src/app/user/components/user-nav.component.ts, src/app/user/user-routing.module.ts, src/app/user/user.module.ts
=> feat: user profile modification

src/app/core/services/state.service.ts, src/app/shared/components/community-navigation.component.ts, src/app/shared/components/navigation.component.ts, src/app/shared/components/secondaryNav.scss, src/app/shared/components/store-navigation.component.ts
=> feat: mouse over nav reset

src/app/core/services/state.service.ts, src/app/shared/components/community-navigation.component.ts, src/app/shared/components/nav-fixed.directive.ts, src/app/shared/components/store-navigation.component.ts, src/app/shared/components/sub-nav-fixed.directive.ts
fixed상태에서 마우스 위치에 따른 서브메뉴 숨기기
서브메뉴 숨기는 코드 directive에 적용
=> feat: fixed 상태에서 서브메뉴 숨기기

src/app/core/models/store.interface.ts, src/app/core/services/store.service.ts, src/app/store/components/store-detail-components/product-detail.component.ts, src/app/store/components/store-detail-components/product-info.component.ts, src/app/store/components/store-detail-components/product-option.component.ts, src/app/store/components/store-detail-components/product-pic.component.ts, src/app/store/components/store-detail-components/product-qna.component.ts, src/app/store/components/store-detail-components/product-review.component.ts, src/app/store/components/store-detail-components/store-detail.component.ts, src/app/store/store.module.ts
Now all components has data from server
Also routing is done
=> data from server, routing

src/app/core/models/user.interface.ts, src/app/core/services/state.service.ts, src/app/core/services/user.service.ts, src/app/shared/UI/avatar-with-button/avatar-with-button.component.ts, src/app/shared/UI/avatar.module.ts, src/app/shared/components/header.component.ts, src/app/shared/components/navigation.component.ts
=> feat: 유저 정보 받아서 표시

src/app/shared/components/header.component.ts, src/app/shared/components/navigation.component.ts
=> feat:로그아웃 후 유저정보 없으면 오류 발생

src/app/auth/components/signin.component.ts, src/app/community/components/community.component.ts, src/app/community/components/photo.component.ts, src/app/core/services/auth.service.ts, src/app/core/services/common.service.ts, src/app/core/services/store.service.ts, src/app/core/services/user.service.ts, src/app/shared/UI/avatar-with-button/avatar-with-button.component.ts, src/app/shared/components/community-navigation.component.ts, src/app/shared/components/header.component.ts, src/app/shared/components/nav-fixed.directive.ts, src/app/shared/components/navigation.component.ts, src/app/shared/components/product-list.component.ts, src/app/shared/components/store-navigation.component.ts, src/app/shared/components/sub-nav-fixed.directive.ts, src/app/store/components/category.component.ts, src/app/store/components/rank.component.ts, src/app/store/components/store-detail-components/product-info.component.ts, src/app/store/components/store-detail-components/product-option.component.ts, src/app/store/components/store-detail-components/store-detail.component.ts, src/app/store/components/store.component.ts
state.service -> common.service로 이름 변경
이름 변경으로 인한 import 및 참조 수정
=> feat: rename state.service -> common.service

src/app/app.component.ts, src/app/auth.guard.ts, src/app/community/community-routing.module.ts, src/app/community/components/community.component.ts, src/app/community/components/photo.component.ts, src/app/shared/components/header.component.ts, src/app/shared/components/navigation.component.ts, src/app/store/components/category.component.ts, src/app/store/components/rank.component.ts, src/app/store/components/store-detail-components/store-detail.component.ts, src/app/store/components/store.component.ts, src/app/user/components/users.component.ts, src/app/user/user-routing.module.ts
token 보유시 token으로 회원정보 획득 위치 최상단으로 이동
유저 프로필 페이지에 auth.guard 적용
=> feat: token 보유시 로그인 정보 획득 위치 변경

src/app/app.component.ts, src/app/core/services/common.service.ts, src/app/shared/UI/avatar-with-button/avatar-with-button.component.ts, src/app/user/components/user-nav.component.ts
=> feat: user 메뉴 nav 링크 적용

src/app/store/components/store-detail-components/pagination.component.ts, src/app/store/components/store-detail-components/product-info.component.ts, src/app/store/components/store-detail-components/product-option.component.ts, src/app/store/components/store-detail-components/product-qna.component.ts, src/app/store/components/store-detail-components/product-review.component.ts, src/styles.scss
Discount-rate: Added discount rate, original price
Pagination: Done with numbers & need to activate right/left buttons.
=> Add discount-rate, working on pagination

src/app/store/components/store-detail-components/basket-modal.component.ts, src/app/store/components/store-detail-components/pagination.component.ts, src/app/store/components/store-detail-components/product-delivery.component.ts, src/app/store/components/store-detail-components/product-info.component.ts, src/app/store/components/store-detail-components/product-nav.component.ts, src/app/store/components/store-detail-components/product-option.component.ts, src/app/store/components/store-detail-components/product-qna.component.ts, src/app/store/components/store-detail-components/product-review.component.ts, src/app/store/components/store-detail-components/store-detail.component.ts, src/app/store/store.module.ts
Finished pagination, position-related bug, navigation scroll event.
Currently working on basket-modal component.
It only has show & hide function for now.
Planning to add routing & http post request.
=> Almost done with store-detail component

src/app/shared/components/product-list.component.ts, src/app/shared/shared.module.ts, src/app/store/components/category.component.ts, src/app/store/components/sort-filter.component.ts, src/app/store/components/store.component.ts, src/app/store/store.module.ts
=> Feat: hover zoomin function now active

src/app/store/components/store-detail-components/pagination.component.ts
There was a bug, so I fixed it
And simplified the code.
=> Feat: Fix pagination

src/app/core/models/cart.interface.ts, src/app/core/services/cart.service.ts, src/app/store/components/store-detail-components/pagination.component.ts, src/app/store/components/store-detail-components/product-option.component.ts, src/app/store/components/store-detail-components/store-detail.component.ts
There was a bug on pagination function, so I fixed it by adding some code.
I added 2 services.
One is for cart, and the other is for payment.
Couldn't test it yet, because of login failure.
=> Fix a bug, Add services

src/app/community/community-routing.module.ts, src/app/shared/components/community-navigation.component.ts
=> feat: routing modify

src/app/store/components/store-detail-components/cart-modal.component.ts, src/app/store/components/store-detail-components/cart-modal.scss, src/app/store/components/store-detail-components/product-nav.component.ts, src/app/store/components/store-detail-components/product-nav.scss, src/app/store/components/store-detail-components/product-option.component.ts, src/app/store/components/store-detail-components/product-option.scss, src/app/store/components/store-detail-components/product-pic.component.ts, src/app/store/components/store-detail-components/product-pic.scss, src/app/store/components/store-detail-components/product-qna.component.ts, src/app/store/components/store-detail-components/product-qna.scss, src/app/store/components/store-detail-components/product-review.component.ts, src/app/store/components/store-detail-components/product-review.scss, src/app/store/components/store-detail-components/store-detail.component.ts, src/app/store/components/store-detail-components/store-detail.scss, src/styles.scss
All the components in store-detail-components folder have their own
.scss files.
=> Add .scss files

src/app/cart/components/cart.component.ts
=> feat: cart httpErrorResponse

src/app/shared/UI/avatar-with-button/avatar-with-button.component.ts
=> feat: profile pic

src/app/community/components/community.component.ts, src/app/store/components/store.component.ts
=> Feat: store carousel now active

src/app/core/models/chosen-option.interface.ts, src/app/core/services/cart.service.ts, src/app/store/components/store-detail-components/product-option.component.ts, src/app/store/components/store-detail-components/store-detail.component.ts
Now it sends all the options at one time.
=> Edit intoCart function

src/app/community/components/community.component.ts
=> Feat: community home on progress 50%

src/app/community/components/photo-detail-components/photo-article.component.ts, src/app/community/components/photo-detail-components/photo-detail.component.ts, src/app/core/models/cart.interface.ts, src/app/core/services/cart.service.ts, src/app/core/services/community.service.ts, src/app/store/components/store-detail-components/store-detail.component.ts
Direct purchasing is now available.
=> Finished buyProduct function

src/app/cart/cart.module.ts, src/app/cart/components/cart-item-filter.pipe.ts, src/app/cart/components/cart.component.ts, src/app/core/models/cart.interface.ts, src/app/core/services/cart.service.ts
장바구니 항목 분류에 파이프 사용
cartService 항목 수정
=> feat: add pipe in cart

src/app/cart/components/cart.component.ts, src/app/cart/components/cart.scss, src/app/cart/components/item-cards.component.ts, src/app/cart/components/item-cards.scss, src/app/core/services/cart.service.ts, src/app/shared/components/navigation.component.ts
장바구니에서 특정 아이템 삭제, 선택된 모든 아이템 삭제
삭제 후 장바구니 갱신
장바구니 리스트 메소드 위치 변경, 각 페이지 -> service
=> 장바구니에서 아이템 삭제

src/app/cart/components/cart.component.ts, src/app/cart/components/item-cards.component.ts, src/app/core/models/cart.interface.ts, src/app/core/services/cart.service.ts
=> 장바구니 수량 변경

src/app/app-routing.module.ts, src/app/app.module.ts, src/app/common.component.ts, src/app/shared/components/community-navigation.component.ts, src/app/shared/components/navigation.component.ts, src/app/shared/components/store-navigation.component.ts, src/app/shared/directive/blue-font.directive.ts, src/app/shared/directive/opacity-dot7-font.directive.ts, src/app/shared/shared.module.ts
directive 추가 : blue font, opacity0.7
공통 모듈 확인 추가
=> feat: add directive

src/app/community/components/community.component.ts
=> Feat: minor changes to buttons

src/app/app.component.ts
scroll to top on router.navigation
=> scroll to top on router.navigation 

src/app/shared/components/product-list.component.ts, src/app/shared/components/rank-crown.component.ts, src/app/shared/shared.module.ts
=> Feat: crown module separated

src/app/user/components/users.component.ts
=> Feat: wrong links removed

src/app/shared/components/header.component.ts, src/app/shared/components/navigation.component.ts, src/app/shared/components/navigation.scss, src/app/shared/components/pop-up.component.ts
=> feat: modify popup

src/app/shared/components/cart-hover.directive.ts
=> Feat: console.log removed
